# 异常机制

## 异常的捕获和处理

```java
try {
    //可能抛出异常的语句
}catch(SomeException1 e) {
    ...
}catch(SomeException2 e) {
    ...
}finally {
    ...
}
```

* try代码段包含可能产生异常的代码
* try代码段后跟有一个或多个catch代码段
* 每个catch代码段声明其能处理的一种特定类型的异常并提供处理的方法
* 当异常发生时，程序会中止当前的流程，根据获取异常的类型去执行相应的catch代码段
* finally段的代码无论是否发生异常都有执行

### try语句

* try{...}语句指定了一段代码，该段代码就是一次捕获并处理例外的范围
* 在执行过程中，该段代码可能会产生并抛出一种或几种类型的异常对象，它后面的catch语句要分别对这些异常做相应的处理
* 如果没有例外产生，所有的catch代码段都被略过不执行

### catch语句

* 在catch语句块中是对异常进行处理的代码，每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象
* 在catch中声明的异常对象(catch(SomeException e))封装了异常事件发生的信息，在catch语句块中可以使用这个对象的一些方法获取这些信息
* 例如：
  * getMessage()方法，用来得到有关异常事件的信息
  * printStackTrace()方法，用来跟踪异常事件发生时执行堆栈的内容

### finally语句

* finally语句为异常处理提供一个统一的出口，使得在控制流程	转到程序的其他部分以前，能够对程序的状态做统一的管理
* 无论try所指定的程序块中是否抛出例外，finally所指定的代码 都要被执行
* 通常在finally语句中可以进行资源的清除工作，如：
  * 关闭打开的文件
  * 删除临时文件
  * ...

![异常机制][1]

每一步都依赖于上一步，一旦某一步出现问题，为了不让程序崩溃，我们应该有一段代码用于防范每一种情况：

![异常机制][2]

这段代码确实把每一种情况都考虑到了，但是有两个缺陷：

* 可读性差
* 难以修改

这时候用上异常机制会很有用：

![异常机制][3]

![异常机制][4]

![异常机制][5]

## 异常的抛出与声明

如果要抛出异常，抛出的东西必须继承`Throwable`类，并且会抛出异常的函数必须声明`throws`的异常：
`````````````java
public static void readFile() throws OpenException {
		if(open() == -1) {
			throw new OpenException();
		}
	}
`````````````
所有调用这个函数的地方必须做好准备，要么`try catch`，要么声明`throws`

![异常机制][6]

![异常机制][7]

![异常机制](https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B613.png)

## 异常捕捉时的匹配：

![异常机制][8]

![异常机制][9]

![异常机制][10]

## 异常遇到继承

![异常机制][11]

![异常机制][12]


[1]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B61.png
[2]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B62.png
[3]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B63.png
[4]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B64.png
[5]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B65.png
[6]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B66.png
[7]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B67.png
[8]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B68.png
[9]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B69.png
[10]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B610.png
[11]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B611.png
[12]: https://github.com/LibraTang/Pics/blob/master/Java-Notes/%E5%BC%82%E5%B8%B8%E6%9C%BA%E5%88%B612.png

## 使用自定义的异常

使用自定义异常一般有如下步骤：

1. 通过继承java.lang.Exception类声明自己的异常类
2. 在方法适当的位置生成自定义异常的实例，并用throw语句抛出
3. 在方法的声明部分用throws语句声明该方法可能抛出的异常

```java
class MyException extends Exception {
    private int id;
    public MyException(String message, int id) {
        super(message);
        this.id = id;
    }
    public int getId() {
        return id;
    }
}
```

**注意**：

重写方法需要抛出与原方法所抛出异常类型一致异常或不抛出异常